# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HT_PyOpenCV.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(3125, 1943)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 0, 401, 591))
        self.textEdit.setObjectName("textEdit")
        self.btnDisplayImage = QtWidgets.QPushButton(self.centralwidget)
        self.btnDisplayImage.setGeometry(QtCore.QRect(0, 10, 151, 61))
        self.btnDisplayImage.setObjectName("btnDisplayImage")
        self.gBoxBinaryPro = QtWidgets.QGroupBox(self.centralwidget)
        self.gBoxBinaryPro.setGeometry(QtCore.QRect(10, 630, 361, 171))
        self.gBoxBinaryPro.setObjectName("gBoxBinaryPro")
        self.lineEdit_threshold = QtWidgets.QLineEdit(self.gBoxBinaryPro)
        self.lineEdit_threshold.setGeometry(QtCore.QRect(10, 70, 131, 31))
        self.lineEdit_threshold.setText("")
        self.lineEdit_threshold.setObjectName("lineEdit_threshold")
        self.lineEdit_maxVal = QtWidgets.QLineEdit(self.gBoxBinaryPro)
        self.lineEdit_maxVal.setGeometry(QtCore.QRect(170, 70, 121, 31))
        self.lineEdit_maxVal.setObjectName("lineEdit_maxVal")
        self.label_2 = QtWidgets.QLabel(self.gBoxBinaryPro)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.gBoxBinaryPro)
        self.label_3.setGeometry(QtCore.QRect(170, 50, 81, 18))
        self.label_3.setObjectName("label_3")
        self.btnDisGray = QtWidgets.QPushButton(self.gBoxBinaryPro)
        self.btnDisGray.setGeometry(QtCore.QRect(10, 110, 151, 61))
        self.btnDisGray.setObjectName("btnDisGray")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(590, 10, 2501, 1851))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 2471, 1801))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("C:/Users/zhjd/.designer/backup/ShowImage.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 3125, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnDisplayImage.setText(_translate("MainWindow", "原图显示"))
        self.gBoxBinaryPro.setTitle(_translate("MainWindow", "图像二值化处理"))
        self.label_2.setText(_translate("MainWindow", "当前阈值"))
        self.label_3.setText(_translate("MainWindow", "最大阈值"))
        self.btnDisGray.setText(_translate("MainWindow", "二值化处理"))
        self.groupBox.setTitle(_translate("MainWindow", "图像显示"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
